import "./styles/Popup.css"

/**
 * Popup Component
 *
 * Displays the Terms and Conditions agreement required on first launch
 * of the extension. Shows the full legal text, instructions, and an
 * “Accept” button that stores the user's consent.
 * 
 * @returns {JSX.Element} The Terms and Conditions popup UI.
 */
export default function Popup({ setAccepted }) {
  const handleAccept = () => {
    chrome.storage.sync.set({ accepted: true }, () => {
        setAccepted(true);
    })
  }
  return (
    <div className="popup-content">
      <div className="popup-top-container">
        <div className="popup-agreement">AGREEMENT</div>
        <div className="popup-title">Terms and Conditions</div>
        <div className="popup-date">Last Updated on 22/11/2025</div>
        <hr className="popup-line"></hr>
      </div>
      <div className="popup-content-container">
        <div className="popup-terms-title">1. Description of Service</div>
        <div className="popup-terms-text">Notiflow is a Chrome extension that helps users manage and organize schedule-related information. The Extension may:</div>
        <ul className="popup-terms-list">
          <li>Access and read data rendered through the <strong>Canvas API</strong> (or Canvas LMS pages).</li>
          <li>Process course-related information (such as assignments, deadlines, or schedule items).</li>
          <li>Export or convert certain information into iCal or similar calendar formats.</li>
          <li>Scrape pages such as exam schedules to extract relevant dates and organizational details.</li>
        </ul>
        <div className="popup-terms-text">Notiflow does not store, transmit, or sell personal data externally. All processing occurs locally within the user’s browser unless explicitly stated otherwise</div>
        <hr className="popup-line"></hr>
        <div className="popup-terms-title">2. User Data Access and Consent</div>
        <div className="popup-terms-text">By installing and using Notiflow, you acknowledge and agree that:</div>
        <ul className="popup-terms-list">
          <li>The Extension may read data displayed on Canvas or other educational pages you visit.</li>
          <li>The Extension may parse information such as assignments, deadlines, event titles, exam data, or similar academic content.</li>
          <li>The Extension may transform this data into calendar entries or other organizational formats for your personal use.</li>
          <li>You provide consent for Notiflow to access and process this information solely for its core functionality.</li>
        </ul>
        <div className="popup-terms-text">Notiflow does not intentionally collect sensitive personal information (e.g., grades, personal identifiers) unless such information is part of the content you load on your own device.</div>
        <hr className="popup-line"></hr>
        <div class="popup-terms-title">3. No Responsibility for User Data</div>
        <div class="popup-terms-text">Notiflow is provided “as is” and does not assume responsibility for:</div>
        <ul class="popup-terms-list">
          <li>The accuracy, completeness, or reliability of data extracted from Canvas or exam pages.</li>
          <li>Any loss, alteration, or misuse of your data resulting from your device, browser, or third-party services.</li>
          <li>Any unintended calendar entries, incorrect data parsing, or scheduling errors.</li>
        </ul>
        <div class="popup-terms-text">You are solely responsible for verifying any calendar information generated by the Extension.</div>
        <hr class="popup-line" />

        <div class="popup-terms-title">4. No Liability</div>
        <div class="popup-terms-text">To the maximum extent permitted by law, Notiflow and its developers shall not be liable for:</div>
        <ul class="popup-terms-list">
          <li>Damages resulting from your use or inability to use the Extension.</li>
          <li>Data inaccuracies, missed deadlines, scheduling mistakes, or academic consequences.</li>
          <li>Unauthorized access to your data resulting from malware, browser vulnerabilities, or user actions.</li>
        </ul>
        <div class="popup-terms-text">Your use of Notiflow is entirely at your own risk.</div>
        <hr class="popup-line" />

        <div class="popup-terms-title">5. Permissions</div>
        <div class="popup-terms-text">Notiflow may require certain browser permissions, such as:</div>
        <ul class="popup-terms-list">
          <li>Access to pages you visit (for reading Canvas/exam information).</li>
          <li>Access to local storage (for saving settings).</li>
          <li>Scripting permissions (to extract schedule data).</li>
        </ul>
        <div class="popup-terms-text">By accepting these Terms, you grant these permissions for the sole purpose of enabling Notiflow’s features.</div>
        <hr class="popup-line" />

        <div class="popup-terms-title">6. Updates</div>
        <div class="popup-terms-text">Notiflow may be updated automatically through the Chrome Web Store. Continued use after updates constitutes acceptance of the updated Terms.</div>
        <hr class="popup-line" />

        <div class="popup-terms-title">7. Termination</div>
        <div class="popup-terms-text">You may stop using Notiflow at any time by removing the Extension from your browser. Notiflow may suspend or discontinue the Extension at any time without prior notice.</div>
        <hr class="popup-line" />

        <div class="popup-terms-title">8. Acceptance of Terms</div>
        <div class="popup-terms-text">By clicking “Accept”, installing, or using Notiflow, you:</div>
        <ul class="popup-terms-list">
          <li>Confirm you have read and understood these Terms.</li>
          <li>Agree to all outlined permissions and data-processing practices.</li>
          <li>Consent to the extraction and conversion of Canvas/exam data for personal use.</li>
        </ul>
        <div class="popup-terms-text">If you do not agree, do not use the Extension.</div>
        <hr class="popup-line" />
      </div>
      <button onClick={handleAccept}>Accept</button>
    </div>
  );
}
